# Intrdoducing Pandas Objects

## The Pandas Series Object

In [1]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [2]:
data.values

array([ 0.25,  0.5 ,  0.75,  1.  ])

In [3]:
data[1]

0.5

In [4]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### Series as generalized Numpy array

In [5]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [6]:
data['b']

0.5

In [7]:
data = pd.Series([0.25,0.5,0.75,1.0],index=[2,3,5,7])
data

2    0.25
3    0.50
5    0.75
7    1.00
dtype: float64

In [8]:
data[5]

0.75

### Series as specialized dictionary

In [9]:
population_dict = {'California':38332521,
             'Texas':26448193,
             'New York':19651127,
             'Florida':19552860,
             'Illionis':12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illionis      12882135
New York      19651127
Texas         26448193
dtype: int64

In [10]:
population['Texas']

26448193

In [11]:
population['California':'Illionis']

California    38332521
Florida       19552860
Illionis      12882135
dtype: int64

### Constructing Series objects

In [12]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [13]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [14]:
pd.Series({2:'a',1:'b',3:'c'})

1    b
2    a
3    c
dtype: object

In [15]:
pd.Series({2:'a',1:'b',3:'c'},index = [3,2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

### DataFrame as a generalized Numpy array

In [16]:
area_dict = {'California':423976,
             'Texas':695662,
             'New York':141297,
             'Florida':170312,
             'Illionis':149995}
area = pd.Series(area_dict)
area

California    423976
Florida       170312
Illionis      149995
New York      141297
Texas         695662
dtype: int64

In [17]:
stats = pd.DataFrame({'population':population,'area':area})
stats

area  population
California  423976    38332521
Florida     170312    19552860
Illionis    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [18]:
stats.index

Index(['California', 'Florida', 'Illionis', 'New York', 'Texas'], dtype='object')

In [19]:
stats.columns

Index(['area', 'population'], dtype='object')

### DataFrame as specialized dictionary

In [20]:
stats['area']

California    423976
Florida       170312
Illionis      149995
New York      141297
Texas         695662
Name: area, dtype: int64

### Consttucting DataFrame objects

#### From a single Series object

In [21]:
pd.DataFrame(population,columns=['population'])

population
California    38332521
Florida       19552860
Illionis      12882135
New York      19651127
Texas         26448193

#### From a list of dicts

In [22]:
data = [{'a':i,'b':2*i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

#### From a dictionary of Series objects

In [23]:
pd.DataFrame({'population':population,'area':area})

area  population
California  423976    38332521
Florida     170312    19552860
Illionis    149995    12882135
New York    141297    19651127
Texas       695662    26448193

#### From a two-dimensional NumPy array

In [24]:
import numpy as np

In [25]:
pd.DataFrame(np.random.rand(3,2),columns=['foo','bar'],index=['a','b','c'])

foo       bar
a  0.645224  0.824070
b  0.331600  0.403604
c  0.820552  0.317264

#### From a Numpy structured array

In [26]:
A = np.zeros(3,dtype=[('A','i8'),('B','f8')])
A

array([(0,  0.), (0,  0.), (0,  0.)],
      dtype=[('A', '<i8'), ('B', '<f8')])

In [27]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

In [28]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

In [29]:
ind[1]

3

In [30]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [31]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64


In [32]:
#error ,cannot be modified via the normal means
#int[1]=3

TypeError: 'type' object does not support item assignment

In [33]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [34]:
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [35]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [37]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

# Data Indexing and Selection

## Data Selection in Series

### Series as dictionary

In [54]:
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [44]:
data['b']

0.5

In [45]:
'a' in data

True

In [46]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [47]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [62]:
data['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [63]:
data['b']=1.2
data

a    0.25
b    1.20
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as one-dimensional array

In [55]:
#slicing by explicit index 显式索引切片
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [56]:
#slicing by implicit integer index 隐式索引切片
data[0:2]

a    0.25
b    0.50
dtype: float64

In [64]:
#masking
data[(data>0.3) & (data<0.8)]

c    0.75
dtype: float64

In [65]:
#fancy indexing
data[['a','e']]

a    0.25
e    1.25
dtype: float64

### indexers:loc,iloc,and ix

In [66]:
data = pd.Series(['a','b','c'],index = [1,3,5])
data

1    a
3    b
5    c
dtype: object

In [69]:
#explicit index when indexing
data[3]

'b'

In [70]:
#implicit index when indexing
data[1:3]

3    b
5    c
dtype: object

In [71]:
#索引值loc  显式  recommend
data.loc[1]

'a'

In [72]:
data.loc[1:3]

1    a
3    b
dtype: object

In [76]:
#索引位置iloc 隐式
data.iloc[2]

'c'

In [77]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Data Selection in DataFrame

### DataFrame as a dictionary

In [80]:
area = pd.Series({'California':423976,
             'Texas':695662,
             'New York':141297,
             'Florida':170312,
             'Illionis':149995})
pop = pd.Series({'California':38332521,
             'Texas':26448193,
             'New York':19651127,
             'Florida':19552860,
             'Illionis':12882135})
data = pd.DataFrame({'area':area,'pop':pop})
data

area       pop
California  423976  38332521
Florida     170312  19552860
Illionis    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [81]:
#accessed via dictionary-style indexing fo the column name
data['area']

California    423976
Florida       170312
Illionis      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [82]:
#attribute-style access with column names
#not recommend
data.area

California    423976
Florida       170312
Illionis      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [83]:
data.area is data['area']

True

In [84]:
#不推荐使用属性方式 会与自带函数名称冲突
#data.pop in data['pop']

TypeError: 'DataFrame' objects are mutable, thus they cannot be hashed

In [86]:
data['density'] = data['pop']/data['area']
data

area       pop     density
California  423976  38332521   90.412007
Florida     170312  19552860  114.806121
Illionis    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

### DataFrame as two-dimensional array

In [87]:
data.values

array([[  4.23976000e+05,   3.83325210e+07,   9.04120068e+01],
       [  1.70312000e+05,   1.95528600e+07,   1.14806121e+02],
       [  1.49995000e+05,   1.28821350e+07,   8.58837628e+01],
       [  1.41297000e+05,   1.96511270e+07,   1.39076746e+02],
       [  6.95662000e+05,   2.64481930e+07,   3.80187404e+01]])

In [88]:
#transpose
data.T

California       Florida      Illionis      New York         Texas
area     4.239760e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041201e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

In [89]:
data.values[0]

array([  4.23976000e+05,   3.83325210e+07,   9.04120068e+01])

In [90]:
data['area']

California    423976
Florida       170312
Illionis      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [93]:
#二元list隐式索引获取 iloc
data.iloc[:3,:2]
#data.iloc[0:3,0:2]

area       pop
California  423976  38332521
Florida     170312  19552860
Illionis    149995  12882135

In [92]:
#二元list显式索引获取 loc
data.loc[:'Illionis',:'pop']

area       pop
California  423976  38332521
Florida     170312  19552860
Illionis    149995  12882135

In [94]:
##二元list混合索引获取 ix
data.ix[:3,:'pop']

area       pop
California  423976  38332521
Florida     170312  19552860
Illionis    149995  12882135

In [95]:
#combine masking and fancy indexing
data.loc[data.density >100,['pop','density']]

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

In [97]:
data.iloc[0,2] = 90
data

area       pop     density
California  423976  38332521   90.000000
Florida     170312  19552860  114.806121
Illionis    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

### Additional indeing conventions

In [98]:
data['Florida':'Illionis']

area       pop     density
Florida   170312  19552860  114.806121
Illionis  149995  12882135   85.883763

In [99]:
data[1:3]

area       pop     density
Florida   170312  19552860  114.806121
Illionis  149995  12882135   85.883763

In [100]:
#bool slices
data[data['density'] > 100]

area       pop     density
Florida   170312  19552860  114.806121
New York  141297  19651127  139.076746

# Operating on Data in Pandas

## Ufuncs:Index Preservation

In [101]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [102]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [103]:
#指数
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

## UFuncs:Index Alignment

### Index alignment in Series

In [105]:
area = pd.Series({'Alaska':1723337,'Texas':695662,'California':423976},name ='area')
population = pd.Series({'California':38332521,
             'Texas':26448193,
             'New York':19651127},name='population')
population/area

Alaska              NaN
California    90.412007
New York            NaN
Texas         38.018740
dtype: float64

In [106]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [107]:
A = pd.Series([2,4,6],index=[0,1,2])
B = pd.Series([1,3,5],index = [1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [108]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index alignment in DataFrame

In [110]:
A = pd.DataFrame(rng.randint(0,20,(2,2)),columns=list('AB'))
A

A   B
0   0  11
1  11  16

In [111]:
B = pd.DataFrame(rng.randint(0,10,(3,3)),columns=list('BAC'))
B

B  A  C
0  9  2  6
1  3  8  2
2  4  2  6

In [112]:
A+B

A     B   C
0   2.0  20.0 NaN
1  19.0  19.0 NaN
2   NaN   NaN NaN

In [115]:
#均值填充
fill = A.stack().mean()
A.add(B,fill_value=fill)

A     B     C
0   2.0  20.0  15.5
1  19.0  19.0  11.5
2  11.5  13.5  15.5

### Ufuncs：Operations Between DataFrame and Series

In [116]:
A = rng.randint(10,size=(3,4))
A

array([[4, 8, 6, 1],
       [3, 8, 1, 9],
       [8, 9, 4, 1]])

In [117]:
A -A[0]

array([[ 0,  0,  0,  0],
       [-1,  0, -5,  8],
       [ 4,  1, -2,  0]])

In [119]:
# - 0row
df = pd.DataFrame(A,columns=list('QRST'))
print(df)
df -df.iloc[0]

   Q  R  S  T
0  4  8  6  1
1  3  8  1  9
2  8  9  4  1


Q  R  S  T
0  0  0  0  0
1 -1  0 -5  8
2  4  1 -2  0

In [120]:
# - R col
df.subtract(df['R'],axis = 0 )

Q  R  S  T
0 -4  0 -2 -7
1 -5  0 -7  1
2 -1  0 -5 -8

In [122]:
#half row
halfrow = df.iloc[0,::2]
halfrow

Q    4
S    6
Name: 0, dtype: int64

In [124]:
print (df)
print (halfrow)
print (df - halfrow)

   Q  R  S  T
0  4  8  6  1
1  3  8  1  9
2  8  9  4  1
Q    4
S    6
Name: 0, dtype: int64
     Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN -5.0 NaN
2  4.0 NaN -2.0 NaN


# Handing Missing Data

## Trade-Offs in Missing Data conventions

## Missing Data in Pandas

### None:Pythonic missing data

In [125]:
vals1 = np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [126]:
for dtype in ['object','int']:
    print ("dtype = ",dtype)
    %timeit np.arange(1E6,dtype=dtype).sum()
    print()


dtype =  object
85.5 ms ± 1.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype =  int
1.69 ms ± 21.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [127]:
#None sum error
#vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### NaN:Missing numerical data

In [128]:
vals2 = np.array([1,np.nan,3,4])
vals2.dtype

dtype('float64')

In [133]:
vals2

array([  1.,  nan,   3.,   4.])

In [129]:
1+np.nan

nan

In [131]:
vals2.sum(),vals2.min(),vals2.max()

(nan, nan, nan)

In [132]:
np.nansum(vals2),np.nanmin(vals2),np.nanmax(vals2)

(8.0, 1.0, 4.0)

### Nan and None in Pandas

In [134]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [139]:
x = pd.Series(range(2),dtype=int)
x

0    0
1    1
dtype: int64

In [138]:
#set a value in int array to np.nan ,it will upcast to a floating-point type
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [140]:
x[0] = np.nan
x

0    NaN
1    1.0
dtype: float64

## Operating on Null Values

### Detecting null values

In [141]:
data = pd.Series([1,np.nan,'hello',None])

In [143]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [144]:
data[data.notnull()]

0        1
2    hello
dtype: object

### Dropping null values

In [145]:
data.dropna()

0        1
2    hello
dtype: object

In [147]:
df = pd.DataFrame([[1,np.nan,2],
                  [2,3,5],
                  [np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [148]:
#dropna will dorp all rows
df.dropna()

0    1  2
1  2.0  3.0  5

In [149]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [151]:
df[3]= np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [157]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [158]:
#thresh :minimum number of non-null values for the row/column to be kept
df.dropna(axis='rows',thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

### Filling null values

In [160]:
data = pd.Series([1,np.nan,2,None,3],index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [161]:
#int fill
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [162]:
#forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [163]:
#back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [166]:
print(df)
df.fillna(method='ffill',axis =1)

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN


0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# Hierarchical Indexing

## A Multiply Indexed Series

### The bad way

In [168]:
index = [('California',2000),('California',2010),('New York',2000),('New York',2010),
         ('Texas',2000), ('Texas',2010)]
populations = [33871648,37253956,18976457,19378102,20851820,25145561]
pop = pd.Series(populations,index = index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [169]:
pop[('California',2010):('Texas',2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [170]:
#select all values from 2010 difficult
pop[[i for i in pop.index if i[1] == 2010 ]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

### The better way:Pandas MultiIndex 

In [171]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [173]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [174]:
#access all data for which the second index is 2010
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

### MultiIndex as extra dimension 

In [175]:
#unstack
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [176]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [178]:
pop_df = pd.DataFrame({'total':pop,'under18':[9267089,9284094,4687374,4318033,5906301,6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [183]:
pop_df.unstack()

total            under18         
                2000      2010     2000     2010
California  33871648  37253956  9267089  9284094
New York    18976457  19378102  4687374  4318033
Texas       20851820  25145561  5906301  6879014

In [181]:
f_u18=pop_df['under18']/pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

## Methods of MultiIndex Creation

In [187]:
#simply pass alist of two or more index arrays to the constuctor
df = pd.DataFrame(np.random.rand(4,2),index=[['a','a','b','b'],
                                            [1,2,1,2]],
                 columns=['data1','data2'])
df

data1     data2
a 1  0.136265  0.478338
  2  0.972411  0.924305
b 1  0.705425  0.632860
  2  0.243919  0.999446

In [188]:
df.unstack()

data1               data2          
          1         2         1         2
a  0.136265  0.972411  0.478338  0.924305
b  0.705425  0.243919  0.632860  0.999446

In [190]:
data = {('California',2000):33871648,('California',2010):37253956,('New York',2000):18976457,
        ('New York',2010):19378102,('Texas',2000):20851820, ('Texas',2010):25145561}
pd.Series(data)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

### Explicit MultiIndex constructors

In [191]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [192]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [194]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [195]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

### MultiIndex level names

In [198]:
pop.index.names= ['state','year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

### MultiIndex for column

In [201]:
#hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],
                                     ['HR','Temp']],names=['subject','type'])
#mock some data
data = np.round(np.random.randn(4,6),1)
data[:,::2]*= 10
data += 37
#create the DataFrame
health_data = pd.DataFrame(data,index=index,columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      29.0  36.6  36.0  36.4  31.0  36.7
     2      31.0  35.6  31.0  37.5  20.0  35.9
2014 1      44.0  35.1  51.0  35.8  31.0  37.9
     2      38.0  38.5  53.0  36.3  45.0  37.0

In [202]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      36.0  36.4
     2      31.0  37.5
2014 1      51.0  35.8
     2      53.0  36.3

## Indexing and Slicing a MultiIndex

In [203]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [204]:
pop['California',2000]

33871648

In [205]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [206]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [207]:
pop[:,2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [209]:
pop[pop >22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [210]:
pop[['California','Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

### Multiply indexed DataFrames

In [212]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      29.0  36.6  36.0  36.4  31.0  36.7
     2      31.0  35.6  31.0  37.5  20.0  35.9
2014 1      44.0  35.1  51.0  35.8  31.0  37.9
     2      38.0  38.5  53.0  36.3  45.0  37.0

In [213]:
health_data['Guido','HR']

year  visit
2013  1        36.0
      2        31.0
2014  1        51.0
      2        53.0
Name: (Guido, HR), dtype: float64

In [222]:
health_data.iloc[:2,:3]

subject      Bob       Guido
type          HR  Temp    HR
year visit                  
2013 1      29.0  36.6  36.0
     2      31.0  35.6  31.0

In [223]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        29.0
      2        31.0
2014  1        44.0
      2        38.0
Name: (Bob, HR), dtype: float64

In [224]:
health_data.loc[(:,1),(:,HR)]

SyntaxError: invalid syntax (<ipython-input-224-995ff7cabc11>, line 1)

In [226]:
idx = pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      29.0  36.0  31.0
2014 1      44.0  51.0  31.0

## Rearranging Multi-Indeces

###  Sorted and UnSorted indices

In [227]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.188445
      2      0.499896
c     1      0.591689
      2      0.048007
b     1      0.634602
      2      0.480419
dtype: float64

In [228]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'KeyError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [230]:
#层级索引存储后才能切片
data= data.sort_index()

In [231]:
data['a':'b']

char  int
a     1      0.188445
      2      0.499896
b     1      0.634602
      2      0.480419
dtype: float64

### Stacking and unstacking indices

In [239]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      29.0  36.6  36.0  36.4  31.0  36.7
     2      31.0  35.6  31.0  37.5  20.0  35.9
2014 1      44.0  35.1  51.0  35.8  31.0  37.9
     2      38.0  38.5  53.0  36.3  45.0  37.0

In [238]:
health_data.unstack(level=0)

subject   Bob                   Guido                     Sue              \
type       HR        Temp          HR        Temp          HR        Temp   
year     2013  2014  2013  2014  2013  2014  2013  2014  2013  2014  2013   
visit                                                                       
1        29.0  44.0  36.6  35.1  36.0  51.0  36.4  35.8  31.0  31.0  36.7   
2        31.0  38.0  35.6  38.5  31.0  53.0  37.5  36.3  20.0  45.0  35.9   

subject        
type           
year     2014  
visit          
1        37.9  
2        37.0

In [240]:
health_data.unstack(level=1)

subject   Bob                   Guido                     Sue              \
type       HR        Temp          HR        Temp          HR        Temp   
visit       1     2     1     2     1     2     1     2     1     2     1   
year                                                                        
2013     29.0  31.0  36.6  35.6  36.0  31.0  36.4  37.5  31.0  20.0  36.7   
2014     44.0  38.0  35.1  38.5  51.0  53.0  35.8  36.3  31.0  45.0  37.9   

subject        
type           
visit       2  
year           
2013     35.9  
2014     37.0

In [241]:
health_data.unstack().stack()

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      29.0  36.6  36.0  36.4  31.0  36.7
     2      31.0  35.6  31.0  37.5  20.0  35.9
2014 1      44.0  35.1  51.0  35.8  31.0  37.9
     2      38.0  38.5  53.0  36.3  45.0  37.0

### Index setting and resetting

In [242]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [243]:
pop_flat= pop.reset_index(name = 'population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [245]:
pop_flat.set_index(['state','year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [246]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      29.0  36.6  36.0  36.4  31.0  36.7
     2      31.0  35.6  31.0  37.5  20.0  35.9
2014 1      44.0  35.1  51.0  35.8  31.0  37.9
     2      38.0  38.5  53.0  36.3  45.0  37.0

In [249]:
health_data_flat= health_data.reset_index()
health_data_flat

subject  year visit   Bob       Guido         Sue      
type                   HR  Temp    HR  Temp    HR  Temp
0        2013     1  29.0  36.6  36.0  36.4  31.0  36.7
1        2013     2  31.0  35.6  31.0  37.5  20.0  35.9
2        2014     1  44.0  35.1  51.0  35.8  31.0  37.9
3        2014     2  38.0  38.5  53.0  36.3  45.0  37.0

In [253]:
health_data_flat.set_index(['year','visit'])

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      29.0  36.6  36.0  36.4  31.0  36.7
     2      31.0  35.6  31.0  37.5  20.0  35.9
2014 1      44.0  35.1  51.0  35.8  31.0  37.9
     2      38.0  38.5  53.0  36.3  45.0  37.0

## Data Aggregations on Multi-Indices

In [258]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      29.0  36.6  36.0  36.4  31.0  36.7
     2      31.0  35.6  31.0  37.5  20.0  35.9
2014 1      44.0  35.1  51.0  35.8  31.0  37.9
     2      38.0  38.5  53.0  36.3  45.0  37.0

In [259]:
data_mean = health_data.mean(level='year')
data_mean

subject   Bob       Guido          Sue       
type       HR  Temp    HR   Temp    HR   Temp
year                                         
2013     30.0  36.1  33.5  36.95  25.5  36.30
2014     41.0  36.8  52.0  36.05  38.0  37.45

In [262]:
data_mean.mean(axis=1, level='type')

type         HR       Temp
year                      
2013  29.666667  36.450000
2014  43.666667  36.766667