# Covariance Matrix

## Install libraries

In [1]:
import sys
!{sys.executable} -m pip install -r requirements.txt

^C
Operation cancelled by user
You are using pip version 9.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


## Imports

In [2]:
import numpy as np
import quiz_tests

## Hints

### covariance matrix
If we have $m$ stock series, the covariance matrix is an $m \times m$ matrix containing the covariance between each pair of stocks.  We can use [numpy.cov](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html) to get the covariance.  We give it a 2D array in which each row is a stock series, and each column is an observation at the same period of time.

The covariance matrix $\mathbf{P} = 
\begin{bmatrix}
\sigma^2_{1,1} & ... & \sigma^2_{1,m} \\ 
... & ... & ...\\
\sigma_{m,1} & ... & \sigma^2_{m,m}  \\
\end{bmatrix}$

## Quiz

In [5]:
import numpy as np

def covariance_matrix(returns):
    """
    Create a function that takes the return series of a set of stocks
    and calculates the covariance matrix.
    
    Parameters
    ----------
    returns : numpy.ndarray
        2D array containing stock return series in each row.
                
    Returns
    -------
    x : np.ndarray
        A numpy ndarray containing the covariance matrix
    """
    print (returns.shape)
    #covariance matrix of returns
    cov = np.cov(returns)
    print(cov)
    return cov

quiz_tests.test_covariance_matrix(covariance_matrix)

(3, 252)
[[0.08816226 0.08816227 0.08816228]
 [0.08816227 0.08816228 0.08816228]
 [0.08816228 0.08816228 0.08816229]]
Tests Passed


In [6]:
"""Test with a 3 simulated stock return series"""
days_per_year = 252
years = 3
total_days = days_per_year * years

return_market = np.random.normal(loc=0.05, scale=0.3, size=days_per_year)
return_1 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
return_2 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
return_3 = np.random.uniform(low=-0.000001, high=.000001, size=days_per_year) + return_market
returns = np.array([return_1, return_2, return_3])

"""try out your function"""
cov = covariance_matrix(returns)

print("The covariance matrix is {}".format(cov))

[[-0.09971362  0.17523598 -0.09095663  0.46917831 -0.26828079  0.01571087
  -0.22100084  0.21055835  0.05121824 -0.28060598  0.03504963 -0.00359038
   0.12767593  0.36245278  0.10377719  0.13695415  0.2727188   0.09389751
  -0.08572884  0.4169286   0.60638055  0.47261471  0.49167722 -0.14744511
   0.06808977 -0.28702727  0.47851126 -0.0415741   0.47451233  0.29846238
   0.54987525  0.28116866  0.31374396  0.22458068  0.07740484  0.24073661
  -0.02331108  0.44132925 -0.51396097  0.11750595  0.18716076 -0.21038767
  -0.20678265  0.26145698 -0.16408885 -0.0565089  -0.39977515 -0.05651015
   0.30524754  0.18513906  0.19185178  0.04977222  0.36800528  0.26874584
   0.27294529 -0.19782355 -0.81779003  0.35956118  0.11744125 -0.17853013
  -0.04364642 -0.19759451  0.17208463 -0.13539174 -0.121908    0.6918158
   0.02380318 -0.28755831 -0.15561487  0.2957845  -0.21425815  0.03485054
   0.64155124 -0.38980738 -0.33426516  0.18841124  0.11121182 -0.86853755
  -0.09267086 -0.20866484  0.68346188  

If you're stuck, you can also check out the solution [here](m3l4_covariance_solution.ipynb)